In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.Tensor(5, 3)
print(x)


   0.0000    0.0000   -0.0001
   0.0000   -0.0001    0.0000
   0.0000    0.0000    0.0000
   0.0000 -542.0405    0.0000
-518.6362    0.0000   -0.0001
[torch.FloatTensor of size 5x3]



In [4]:
x = torch.rand(5, 3)
print(x)


 0.9024  0.0926  0.5361
 0.4427  0.0162  0.0989
 0.3216  0.5328  0.3075
 0.4725  0.5369  0.1779
 0.0329  0.4575  0.4032
[torch.FloatTensor of size 5x3]



In [5]:
print(x.size())

torch.Size([5, 3])


In [6]:
y = torch.rand(5, 3)
print(x + y)


 1.0042  1.0385  1.1742
 1.3061  0.4530  0.5574
 0.5009  1.4213  0.8453
 1.2463  1.1249  0.2361
 0.3538  1.0251  0.9683
[torch.FloatTensor of size 5x3]



In [7]:
print(torch.add(x, y))


 1.0042  1.0385  1.1742
 1.3061  0.4530  0.5574
 0.5009  1.4213  0.8453
 1.2463  1.1249  0.2361
 0.3538  1.0251  0.9683
[torch.FloatTensor of size 5x3]



In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out = result)
print(result)


 1.0042  1.0385  1.1742
 1.3061  0.4530  0.5574
 0.5009  1.4213  0.8453
 1.2463  1.1249  0.2361
 0.3538  1.0251  0.9683
[torch.FloatTensor of size 5x3]



In [9]:
result = x + y
print(result)


 1.0042  1.0385  1.1742
 1.3061  0.4530  0.5574
 0.5009  1.4213  0.8453
 1.2463  1.1249  0.2361
 0.3538  1.0251  0.9683
[torch.FloatTensor of size 5x3]



In [10]:
y.add_(x)
print(y)


 1.0042  1.0385  1.1742
 1.3061  0.4530  0.5574
 0.5009  1.4213  0.8453
 1.2463  1.1249  0.2361
 0.3538  1.0251  0.9683
[torch.FloatTensor of size 5x3]



In [11]:
print(x[:, 1])


 0.0926
 0.0162
 0.5328
 0.5369
 0.4575
[torch.FloatTensor of size 5]



In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
a = torch.ones(5, 2)
print(a)


 1  1
 1  1
 1  1
 1  1
 1  1
[torch.FloatTensor of size 5x2]



In [15]:
b = a.numpy()
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
a.add_(1)
print(a)
print(b)


 2  2
 2  2
 2  2
 2  2
 2  2
[torch.FloatTensor of size 5x2]

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [19]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x + y)


 0.9979 -1.4761 -0.2014 -1.3453
-0.8565 -0.9501 -3.4234 -0.9851
-2.7409 -0.0122  2.4400  0.4514
-3.0850  2.4431  0.3692  2.9239
[torch.cuda.FloatTensor of size 4x4 (GPU 0)]



/home/nathan/projects/machine_learning/pytorch/lib/python3.5/site-packages/torch/tensor.py:293: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return self.add(other)
